; GENERATED by tools/datagen — DO NOT EDIT BY HAND.
; Pins the binary blobs into their ROM banks (kit spec §3).
.include "hdr.asm"

.BANK 2 SLOT 0
.ORG 0
.SECTION "SceneBank0" FORCE
.incbin "src/data/scenes.bin"
.ENDS

.BANK 6 SLOT 0
.ORG 0
.SECTION "TextBank0" FORCE
.incbin "src/data/texts.bin"
.ENDS
