//! Emitting the generated C data files. Output is stable and
//! deterministic: same inputs, same bytes. `tools/gate-datagen.sh` relies
//! on that.

use std::fmt::Write;

/// The banner every generated file opens with. "Source: demo/" was wrong —
/// datagen runs on whatever project it is given — so the line now names
/// the tool and the way back to the sources instead.
pub const HEADER: &str = "/*\n * GENERATED by tools/datagen — DO NOT EDIT BY HAND.\n * Source: the project passed to datagen. Regenerate with: make data\n */\n";

pub fn u8_array(name: &str, data: &[u8], cols: usize, static_: bool) -> String {
    let mut s = String::new();
    let prefix = if static_ { "static " } else { "" };
    let _ = write!(s, "{}const u8 {}[] = {{\n", prefix, name);
    for chunk in data.chunks(cols) {
        s.push_str("  ");
        for b in chunk {
            let _ = write!(s, "0x{:02X}, ", b);
        }
        s.pop();
        s.push('\n');
    }
    s.push_str("};\n");
    s
}

pub fn u16_array(name: &str, data: &[u16]) -> String {
    let mut s = String::new();
    let _ = write!(s, "const u16 {}[{}] = {{\n", name, data.len());
    for chunk in data.chunks(8) {
        s.push_str("  ");
        for v in chunk {
            let _ = write!(s, "0x{:04X}, ", v);
        }
        s.pop();
        s.push('\n');
    }
    s.push_str("};\n");
    s
}
