// Gabarit de nouveau projet : assets de démarrage embarqués (tileset 6
// tiles, héros + villageois 16x24, fonte de la textbox — repris de demo/)
// et construction du projet minimal sur disque.

import { mkdir } from "@tauri-apps/plugin-fs";
import type { ProjectData } from "./types";
import { newScene } from "./state";
import { saveProject, writeBinaryFile } from "./io";

const TILESET_PNG = "iVBORw0KGgoAAAANSUhEUgAAAGAAAAAQCAMAAADeZIrLAAADAFBMVEUAAAAYWCAwgDBgqEhAQEiAgIi4uMCQcEDIqHAYOJBIeNBgOBjIMDDoyEDw8PAQEBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsQy21AAABAUlEQVR4nJ2T2xKDIAxEidhiQeX//7aEe4JBx50RfNpDsolatAZYFsAD9aVaN6Yfk4ryQepa6I3GBfChegTwXgcJiIURBoBp5vhrLdpaW+7qD8AIRwVkaS1VYPInVJD9AyFZ7sn/OBjgUYvMCKj+mbDviQAkA3x+LGEKMFcV+OqfS8jO0FpUAn4Xsq/+FFBCTu661LEy9QFHQMs33ggAChimiNRQ5r8sQh+wFPLMXwp5LT16sAc+E7oxPTkgjagAMDeATOj9z7POq7BovAIzAwSEc6Q/0Oa1PT9eMG+R2egex01GOacGQDpZh6YZGLECDlAMcBPyzRSJgMspkvbgLeAP/eQbqr5ipc0AAAAASUVORK5CYII=";
const SPRITES_PNG = "iVBORw0KGgoAAAANSUhEUgAAAYAAAAAYCAYAAADzhSolAAABo0lEQVR4nO3cPU4CQRiA4cF4gInhAJzAGEoLY6ysKSyorC3MnmBjOMHGE1BRWFBbWlkS4wk4AMUewGRtNAI7M7JZ3W+/mfepwNkX+ZlkGP6MAQAAAAAAAAAAAAAAAAAAAAAAWgz2/2DtsAoFZbmpNfT09PT0+vqdM9YOq9uz41Bv5m8f3itBT6+9z7Is2BdFQU8fTX8UPBoAEK3a06WHPA8G80l4XLrXTvr+S73PLk6C40URHBbvtZO+/1Lr2QEAQKLcC8B4akbfz5S2Tx9Kutes7e2V7j1Gk9yY8VRHLz1/mf96e4++zn/3ArBamPVyVj99KOles7a3V7r3WC9nxqwWOnrp+cv819t79HX+hz8yoZD0a8ipv4cBWdpeg4Ys3gMAgETt7AC+Ph9aXT6eOw9+uX8NfhGBnj6G/vr9yTn+fHpDTx9Vzw4AABLFAgAAiaotAPbqzrvFCI3R09PT0+vq2QEAAH5YO6y2f1Vu/zx9f3vXsV32ruOb9r7L6KrX/PjT0zfpO9kBlOVm8NvPmP5n31YM11+y/6v/23QRaNsDsfsEn1RYZGPqL54AAAAASUVORK5CYII=";
const FONT_PNG = "iVBORw0KGgoAAAANSUhEUgAAAwAAAAAICAMAAAB55GhMAAADAFBMVEUAAAAQGFLn5+cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa2LNyAAAC1klEQVR4nL1XCXLDIAws+v+j28QG7SER2+3UMyk2Bkl7iKRfI6+I8+/7Zo4/d/D2NQatX+Oaf3rN/JE3OY/Ta9nr1pZfzuYBi/SB45sTmMni5oIZWjnkZ6i7y0e4NN525PoI8HlT8l49NCua9WSMnL+pyz75k506xEHBQdOXrXdS55Y45zrj8/4rlaOBmTOJaN22HibZQLouNSNQ0CJG9ynQYnFUv++L9bmaEzN1hsdYTIAWRQ5wQkaeJ3r+yEEDvohcPzyoUVTED8mD/ZsHQI/fR8jAkkEJ4zwGomiAEVnoaXjkAfmrGS4M3VwsNhIxYAJ4iByBWSLIgbOOVNeJj09YiJc5LL++L+NSMSnwFSG13nbd1NPqqNDCXpABBUFNPjYZzqPuQWlWlVHEr/JwjQCK3wfusdqaBgDQ721FAzAZLsSqTglO3dSpg+JQvukJRkoBc4pdVRrDrmJuCRaJBxq+Uq9kM2AfZTJQYwkGPbBvAGGkMGMKRPy2ulfsHC/W/h1+PpmLeikRqJ02uoAbdrktCD+fyF6H4yZrnajbBkBhJXrIQrm1b4CGeLChCn1kle5momh9MtLmSUKZoK0hIX4JalNP6eUUz4zlRmtxsgGKWoX2DzrUeDr8xN62ATzER+NjHgGk+LFBuAFa3By6aABjZGJl4pVISQj7GuKJLvg90RgmTw78CCdF5C4/P9YG/WCI4e+pfo1TrC/i5jcEk2ECz7/B+ZkLv7vfAMUIBYfk1wYwne40AIP2n3zFXjhJXCrFP0u8/BPoLRD9F6P7en6rBgC2AgHAyRZCxgTOgPBZCtkJrq5JMvknBZUDApkBpG6KVxuJ9YJn5J1wzpsxPB6VAUZBAvd0AP+uCzwThY6fMBhPjl/1Zz4AMOOKsXKhxRO/GlNde/zpvwFkKYXYU9nu/+frYl5r6BsZ/hbaQ34f5opnwOG4qbffi8rH8i9w93Da6deLb1dKIBYsl+RQAAAAAElFTkSuQmCC";

function bytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

// Crée un projet minimal dans `root` (dossier vide) : une scène 30x20 avec
// bordure d'eau, le tileset/les personnages/la fonte de démarrage. Le nom
// du projet est le nom du dossier.
export async function scaffoldProject(root: string): Promise<void> {
  const name = root.split(/[\\/]/).pop() || "projet";
  await mkdir(`${root}/scenes`, { recursive: true });
  await mkdir(`${root}/assets`, { recursive: true });
  await writeBinaryFile(`${root}/assets/tileset.png`, bytes(TILESET_PNG));
  await writeBinaryFile(`${root}/assets/sprites.png`, bytes(SPRITES_PNG));
  await writeBinaryFile(`${root}/assets/font.png`, bytes(FONT_PNG));

  const data: ProjectData = {
    root,
    project: {
      name,
      boot_scene: "scene1",
      scenes: ["scene1"],
      assets: {
        tileset: "assets/tileset.png",
        sprites: "assets/sprites.png",
        font: "assets/font.png",
      },
      musics: [],
      tilesets: ["assets/tileset.png"],
      charsets: ["Héros", "Villageois"],
    },
    scenes: { scene1: newScene("scene1", 30, 20) },
    texts: [],
    screens: {},
    tilesetMeta: { tileset: { autotiles: [], solid: [1, 3, 4], above: [5] } },
  };
  await saveProject(data);
}
