/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 anim_count = 0;

/* the vignette used as the cell sheet, per animation */
const u8 anim_vig[] = {
  0x00,
};

/* bit 0 = loop */
const u8 anim_flags[] = {
  0x00,
};

/* simultaneous cells (layers): track stride = 3L + 2 */
const u8 anim_layers[] = {
  0x00,
};

/* frame count */
const u8 anim_nframes[] = {
  0x00,
};

/* offset of the first frame in anim_track */
const u16 anim_ofs[1] = {
  0x0000,
};

/* flattened track, FIXED stride of 3L + 2 bytes per frame:
                L x [cell (0xFF = empty layer)][signed dx][signed dy]
                then [duration][sound, 0xFF = none] */
const u8 anim_track[] = {
  0x00,
};
