/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

extern const u8 m7w0_chars[];
extern const u16 m7w0_chars_size;
extern const u8 m7w0_meta[];
extern const u8 m7w0_pass[];
extern const u16 m7w0_pal[];
extern const u8 m7w0_map[];

const u8 m7w_count = 1;
const u8 m7w_rot_stride = 16;

const u8 m7w_scene[1] = { 3, };
const u8 *const m7w_chars[1] = { m7w0_chars, };
const u16 *const m7w_chars_sizes[1] = { &m7w0_chars_size, };
const u8 *const m7w_metas[1] = { m7w0_meta, };
const u8 *const m7w_maps[1] = { m7w0_map, };
const u8 *const *const m7w_slicess[1] = { 0, };
const u8 *const m7w_passes[1] = { m7w0_pass, };
const u16 *const m7w_pals[1] = { m7w0_pal, };
const u8 m7w_w[1] = { 32, };
const u8 m7w_h[1] = { 32, };
const u8 m7w_horizon[1] = { 56, };
const u8 m7w_anchor[1] = { 176, };
const u8 m7w_rot[1] = { 16, };
const u16 m7w_sky[1] = { 29256, };
const u8 m7w_skyg[1] = { 0, };
const u16 m7w_skytop[1] = { 0, };
const u16 m7w_skybot[1] = { 0, };
const u8 m7w_skyimg[1] = { 0, };
const u8 *const m7w_skych[1] = { 0, };
const u16 *const m7w_skych_sizes[1] = { 0, };
const u16 *const m7w_skymaps[1] = { 0, };
const u8 m7w_skyh[1] = { 0, };
extern const u8 m7w0_rotab0[];
extern const u8 m7w0_rotcd0[];
extern const u8 m7w0_rotab1[];
extern const u8 m7w0_rotcd1[];
extern const u8 m7w0_rotab2[];
extern const u8 m7w0_rotcd2[];
extern const u8 m7w0_rotab3[];
extern const u8 m7w0_rotcd3[];
extern const u8 m7w0_rotab4[];
extern const u8 m7w0_rotcd4[];
extern const u8 m7w0_rotab5[];
extern const u8 m7w0_rotcd5[];
extern const u8 m7w0_rotab6[];
extern const u8 m7w0_rotcd6[];
extern const u8 m7w0_rotab7[];
extern const u8 m7w0_rotcd7[];
extern const u8 m7w0_rotab8[];
extern const u8 m7w0_rotcd8[];
extern const u8 m7w0_rotab9[];
extern const u8 m7w0_rotcd9[];
extern const u8 m7w0_rotab10[];
extern const u8 m7w0_rotcd10[];
extern const u8 m7w0_rotab11[];
extern const u8 m7w0_rotcd11[];
extern const u8 m7w0_rotab12[];
extern const u8 m7w0_rotcd12[];
extern const u8 m7w0_rotab13[];
extern const u8 m7w0_rotcd13[];
extern const u8 m7w0_rotab14[];
extern const u8 m7w0_rotcd14[];
extern const u8 m7w0_rotab15[];
extern const u8 m7w0_rotcd15[];
const u8 *const m7w_rotab[16] = { m7w0_rotab0, m7w0_rotab1, m7w0_rotab2, m7w0_rotab3, m7w0_rotab4, m7w0_rotab5, m7w0_rotab6, m7w0_rotab7, m7w0_rotab8, m7w0_rotab9, m7w0_rotab10, m7w0_rotab11, m7w0_rotab12, m7w0_rotab13, m7w0_rotab14, m7w0_rotab15, };
const u8 *const m7w_rotcd[16] = { m7w0_rotcd0, m7w0_rotcd1, m7w0_rotcd2, m7w0_rotcd3, m7w0_rotcd4, m7w0_rotcd5, m7w0_rotcd6, m7w0_rotcd7, m7w0_rotcd8, m7w0_rotcd9, m7w0_rotcd10, m7w0_rotcd11, m7w0_rotcd12, m7w0_rotcd13, m7w0_rotcd14, m7w0_rotcd15, };
const u16 m7w_rotox[16] = { 0, 65490, 65451, 65425, 65416, 65425, 65451, 65490, 0, 46, 85, 111, 120, 111, 85, 46, };
const u16 m7w_rotoy[16] = { 120, 111, 85, 46, 0, 65490, 65451, 65425, 65416, 65425, 65451, 65490, 0, 46, 85, 111, };
const u16 m7w_rotcos[16] = { 256, 237, 181, 98, 0, 65438, 65355, 65299, 65280, 65299, 65355, 65438, 0, 98, 181, 237, };
const u16 m7w_rotsin[16] = { 0, 98, 181, 237, 256, 237, 181, 98, 0, 65438, 65355, 65299, 65280, 65299, 65355, 65438, };
