/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 btl_hero_count = 0;
const u8 *const btl_hero_cells[1] = { 0, };
const u16 btl_hero_pals[16] = { 0, };
const u16 btl_hero_maxhp[1] = { 0, };
const u16 btl_hero_maxmp[1] = { 0, };
const u8 btl_hero_speed[1] = { 0, };
const u8 btl_hero_atk[1] = { 0, };
const u8 btl_hero_def[1] = { 0, };
const u8 btl_hero_mag[1] = { 0, };
const u8 btl_hero_mdef[1] = { 0, };
const u8 btl_troop_count = 0;
const u8 btl_troop_back[1] = { 0, };
const u8 btl_troop_n[1] = { 0, };
const u8 btl_troop_pic[1] = { 0, };
const u8 btl_troop_x[1] = { 0, };
const u8 btl_troop_y[1] = { 0, };
const u8 btl_troop_monid[1] = { 0xFF, };
const u8 btl_troop_intro[1] = { 0xFF, };
const u8 btl_digit_cells[1] = { 0, };
const u16 btl_digit_pal[1] = { 0, };
