/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

/* menu de debug en jeu (Start+Select+R) — S6/M1 */
const u8 dbg_enabled = 0;
/* rangée budgets pré-formatée (32 colonnes max) */
const char dbg_banks_txt[] = "SCN 2903/32768 TXT 653/32768";
