/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>


const u8 m7_img_count = 0;
const u8 m7_ramp_count = 0;

const u8 *const m7_img_chars[1] = { 0, };
const u16 *const m7_img_chars_sizes[1] = { 0, };
const u8 *const m7_img_maps[1] = { 0, };
const u16 *const m7_img_pals[1] = { 0, };
const u8 m7_img_wt[1] = { 0, };
const u8 m7_img_ht[1] = { 0, };

const u16 *const m7_ramps[1] = { 0, };
const u8 m7_ramp_lens[1] = { 0, };
