/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

extern const u8 gs0_chars[];
extern const u16 gs0_chars_size;
extern const u16 gs0_meta[];
extern const u8 gs0_prio[];
extern const u16 gs0_pal[];
extern const u8 gs1_chars[];
extern const u16 gs1_chars_size;
extern const u16 gs1_meta[];
extern const u8 gs1_prio[];
extern const u16 gs1_pal[];
extern const u8 gs2_chars[];
extern const u16 gs2_chars_size;
extern const u16 gs2_meta[];
extern const u8 gs2_prio[];
extern const u16 gs2_pal[];
extern const u8 ss0_chars[];
extern const u16 ss0_chars_size;
extern const u16 ss0_pal[];
extern const u8 ss1_chars[];
extern const u16 ss1_chars_size;
extern const u16 ss1_pal[];

const u8 *const gfx_chars[] = {
  gs0_chars,
  gs1_chars,
  gs2_chars,
};

const u16 *const gfx_chars_sizes[] = {
  &gs0_chars_size,
  &gs1_chars_size,
  &gs2_chars_size,
};

const u16 *const gfx_metas[] = {
  gs0_meta,
  gs1_meta,
  gs2_meta,
};

const u8 *const gfx_prios[] = {
  gs0_prio,
  gs1_prio,
  gs2_prio,
};

const u16 *const gfx_pals[] = {
  gs0_pal,
  gs1_pal,
  gs2_pal,
};

const u8 *const sprite_chars[] = {
  ss0_chars,
  ss1_chars,
};

const u16 *const sprite_chars_sizes[] = {
  &ss0_chars_size,
  &ss1_chars_size,
};

const u16 *const sprite_pals[] = {
  ss0_pal,
  ss1_pal,
};
