/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 btl_hero_count = 0;
const u8 *const btl_hero_cells[1] = { 0, };
const u16 btl_hero_pals[16] = { 0, };
const u16 btl_hero_maxhp[1] = { 0, };
const u16 btl_hero_maxmp[1] = { 0, };
const u8 btl_hero_speed[1] = { 0, };
const u8 btl_troop_count = 0;
const u8 btl_troop_back[1] = { 0, };
const u8 btl_troop_n[1] = { 0, };
const u8 btl_troop_pic[1] = { 0, };
const u8 btl_troop_x[1] = { 0, };
const u8 btl_troop_y[1] = { 0, };
const u8 btl_hero_atk[1] = { 0, };
const u8 btl_hero_def[1] = { 0, };
const u16 btl_mon_hp[1] = { 0, };
const u8 btl_mon_atk[1] = { 0, };
const u8 btl_mon_def[1] = { 0, };
const u8 btl_mon_spd[1] = { 0, };
const u16 btl_mon_xp[1] = { 0, };
const u16 btl_mon_gold[1] = { 0, };
const u8 btl_menu_widget = 0xFF;
const u8 btl_hero_mag[1] = { 0, };
const u8 btl_mon_mdef[1] = { 0, };
const u8 btl_act_n = 1;
const u8 btl_act_kind[1] = { 0, };
const u8 btl_act_arg[1] = { 0, };
const u8 btl_skill_mp[1] = { 0, };
const u8 btl_skill_pow[1] = { 0, };
const u8 btl_skill_tgt[1] = { 0, };
const u8 btl_skill_anim[1] = { 0xFF, };
const u8 btl_hero_mdef[1] = { 0, };
const u8 btl_mon_mag[1] = { 0, };
const u8 btl_mon_ai_start[1] = { 0, };
const u8 btl_mon_ai_n[1] = { 0, };
const u8 btl_ai_kind[1] = { 0, };
const u8 btl_ai_arg[1] = { 0, };
const u8 btl_ai_w[1] = { 0, };
const u8 btl_troop_intro[1] = { 0xFF, };
const u8 btl_troop_lowhp[1] = { 0xFF, };
const u8 btl_digit_cells[1] = { 0, };
const u16 btl_digit_pal[1] = { 0, };
const u8 btl_atb_active = 0;
const u8 btl_skill_status[1] = { 0, };
const u8 btl_item_n = 0;
const u16 btl_item_heal[1] = { 0, };
const u8 btl_item_var[1] = { 0, };
