/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 anim_count = 0;

/* vignette servant de planche de cellules, par animation */
const u8 anim_vig[] = {
  0x00,
};

/* bit 0 = boucle */
const u8 anim_flags[] = {
  0x00,
};

/* cellules simultanees (calques) : pas de piste = 3L + 2 */
const u8 anim_layers[] = {
  0x00,
};

/* nombre de frames */
const u8 anim_nframes[] = {
  0x00,
};

/* offset de la premiere frame dans anim_track */
const u16 anim_ofs[1] = {
  0x0000,
};

/* piste aplatie, pas FIXE de 3L + 2 octets par frame :
                L x [cellule (0xFF = calque vide)][dx signe][dy signe]
                puis [duree][son, 0xFF = aucun] */
const u8 anim_track[] = {
  0x00,
};
