/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

/* in-game debug menu (Start+Select+R) — S6/M1 */
const u8 dbg_enabled = 0;
/* pre-formatted budget row (32 columns max) */
const char dbg_banks_txt[] = "SCN 2665/32768 TXT 653/32768";
