/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>


const u8 m7w_count = 0;
const u8 m7w_rot_stride = 16;

const u8 m7w_scene[1] = { 0, };
const u8 *const m7w_chars[1] = { 0, };
const u16 *const m7w_chars_sizes[1] = { 0, };
const u8 *const m7w_metas[1] = { 0, };
const u8 *const m7w_maps[1] = { 0, };
const u16 *const m7w_pals[1] = { 0, };
const u8 m7w_w[1] = { 0, };
const u8 m7w_h[1] = { 0, };
const u8 m7w_horizon[1] = { 0, };
const u8 m7w_anchor[1] = { 0, };
const u8 m7w_rot[1] = { 0, };
const u16 m7w_sky[1] = { 0, };
const u8 m7w_skyg[1] = { 0, };
const u16 m7w_skytop[1] = { 0, };
const u16 m7w_skybot[1] = { 0, };
const u8 m7w_skyimg[1] = { 0, };
const u8 *const m7w_skych[1] = { 0, };
const u16 *const m7w_skych_sizes[1] = { 0, };
const u16 *const m7w_skymaps[1] = { 0, };
const u8 m7w_skyh[1] = { 0, };
const u8 *const m7w_rotp[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const u8 *const m7w_rotr[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const u16 m7w_rotox[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const u16 m7w_rotoy[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const u16 m7w_rotcos[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
const u16 m7w_rotsin[16] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, };
