/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

extern const u8 m7w0_chars[];
extern const u16 m7w0_chars_size;
extern const u8 m7w0_meta[];
extern const u8 m7w0_map[];
extern const u16 m7w0_pal[];

const u8 m7w_count = 1;
const u8 m7w_rot_stride = 16;

const u8 m7w_scene[1] = { 3, };
const u8 *const m7w_chars[1] = { m7w0_chars, };
const u16 *const m7w_chars_sizes[1] = { &m7w0_chars_size, };
const u8 *const m7w_metas[1] = { m7w0_meta, };
const u8 *const m7w_maps[1] = { m7w0_map, };
const u16 *const m7w_pals[1] = { m7w0_pal, };
const u8 m7w_w[1] = { 32, };
const u8 m7w_h[1] = { 32, };
const u8 m7w_horizon[1] = { 56, };
const u8 m7w_anchor[1] = { 176, };
const u8 m7w_rot[1] = { 16, };
const u16 m7w_sky[1] = { 29256, };
const u8 m7w_skyg[1] = { 0, };
const u16 m7w_skytop[1] = { 0, };
const u16 m7w_skybot[1] = { 0, };
const u8 m7w_skyimg[1] = { 0, };
const u8 *const m7w_skych[1] = { 0, };
const u16 *const m7w_skych_sizes[1] = { 0, };
const u16 *const m7w_skymaps[1] = { 0, };
const u8 m7w_skyh[1] = { 0, };
extern const u8 m7w0_rotp0[];
extern const u8 m7w0_rotr0[];
extern const u8 m7w0_rotp1[];
extern const u8 m7w0_rotr1[];
extern const u8 m7w0_rotp2[];
extern const u8 m7w0_rotr2[];
extern const u8 m7w0_rotp3[];
extern const u8 m7w0_rotr3[];
extern const u8 m7w0_rotp4[];
extern const u8 m7w0_rotr4[];
extern const u8 m7w0_rotp5[];
extern const u8 m7w0_rotr5[];
extern const u8 m7w0_rotp6[];
extern const u8 m7w0_rotr6[];
extern const u8 m7w0_rotp7[];
extern const u8 m7w0_rotr7[];
extern const u8 m7w0_rotp8[];
extern const u8 m7w0_rotr8[];
extern const u8 m7w0_rotp9[];
extern const u8 m7w0_rotr9[];
extern const u8 m7w0_rotp10[];
extern const u8 m7w0_rotr10[];
extern const u8 m7w0_rotp11[];
extern const u8 m7w0_rotr11[];
extern const u8 m7w0_rotp12[];
extern const u8 m7w0_rotr12[];
extern const u8 m7w0_rotp13[];
extern const u8 m7w0_rotr13[];
extern const u8 m7w0_rotp14[];
extern const u8 m7w0_rotr14[];
extern const u8 m7w0_rotp15[];
extern const u8 m7w0_rotr15[];
const u8 *const m7w_rotp[16] = { m7w0_rotp0, m7w0_rotp1, m7w0_rotp2, m7w0_rotp3, m7w0_rotp4, m7w0_rotp5, m7w0_rotp6, m7w0_rotp7, m7w0_rotp8, m7w0_rotp9, m7w0_rotp10, m7w0_rotp11, m7w0_rotp12, m7w0_rotp13, m7w0_rotp14, m7w0_rotp15, };
const u8 *const m7w_rotr[16] = { m7w0_rotr0, m7w0_rotr1, m7w0_rotr2, m7w0_rotr3, m7w0_rotr4, m7w0_rotr5, m7w0_rotr6, m7w0_rotr7, m7w0_rotr8, m7w0_rotr9, m7w0_rotr10, m7w0_rotr11, m7w0_rotr12, m7w0_rotr13, m7w0_rotr14, m7w0_rotr15, };
const u16 m7w_rotox[16] = { 0, 65490, 65451, 65425, 65416, 65425, 65451, 65490, 0, 46, 85, 111, 120, 111, 85, 46, };
const u16 m7w_rotoy[16] = { 120, 111, 85, 46, 0, 65490, 65451, 65425, 65416, 65425, 65451, 65490, 0, 46, 85, 111, };
const u16 m7w_rotcos[16] = { 256, 237, 181, 98, 0, 65438, 65355, 65299, 65280, 65299, 65355, 65438, 0, 98, 181, 237, };
const u16 m7w_rotsin[16] = { 0, 98, 181, 237, 256, 237, 181, 98, 0, 65438, 65355, 65299, 65280, 65299, 65355, 65438, };
