/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>
#include "db_tables.h"

const u8 *const db_tables[] = {
  db_items,
  db_stats,
};
const u8 db_table_sizes[] = {
  6, 10,
};
const u8 db_table_counts[] = {
  2, 2,
};
