/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 db_items[] = {
  0x14, 0x00, 0x1E, 0x11, 0xFF, 0xFF, 0x32, 0x00, 0x04, 0x02, 0xFF, 0xFF,
};
