/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
#include <snes.h>

const u8 ui_ov_x[2] = { 2, 13, };
const u8 ui_ov_y[2] = { 2, 2, };
const u8 ui_ov_w[2] = { 10, 9, };
const u8 ui_ov_h[2] = { 5, 5, };
const u8 ui_ov_var[2] = { 0, 0, };
const u8 ui_ov_type[2] = { 7, 7, };
const u8 ui_ov_frame[2] = { 1, 1, };
const u8 ui_ov_icon[2] = { 0, 0, };
const u8 ui_ov_dir[2] = { 0, 0, };
const u8 ui_ov_pad[2] = { 0, 0, };
const u8 ui_ov_bg[2] = { 0, 0, };
const u8 ui_ov_widget[2] = { 0, 1, };
const u8 ui_ov_picvar[2] = { 255, 255, };
const u8 ui_ov_picn[2] = { 0, 0, };
const u8 ui_ov_picstr[2] = { 0, 0, };
const u8 ui_ov_src[2] = { 255, 255, };
const u8 ui_ov_srcfilt[2] = { 255, 255, };
const u8 ui_ov_srccnt[2] = { 255, 255, };
const u8 ui_ov_maxvar[2] = { 255, 255, };
const u8 ui_ov_maxlo[2] = { 0, 0, };
const u8 ui_ov_maxhi[2] = { 0, 0, };
const u8 ui_ov_font[2] = { 1, 1, };
const u8 ui_widget_vis[2] = { 0, 0, };
const u8 ui_widget_visvar[2] = { 255, 255, };
static const char ui_ov_l0[] = "Attaque\012Objet\012Fuite";
static const char ui_ov_l1[] = "Feu\012Soin\012Foudre";
const char *const ui_ov_label[2] = { ui_ov_l0, ui_ov_l1, };
const u8 ui_hook_move[2] = { 255, 255, };
const u8 ui_hook_confirm[2] = { 255, 255, };
const u8 ui_hook_cancel[2] = { 255, 255, };
const u8 ui_hook_show[2] = { 255, 255, };
const u8 ui_hook_hide[2] = { 255, 255, };
const u8 ui_hook_rowvar[2] = { 255, 255, };
