/*
 * GENERATED by tools/datagen — DO NOT EDIT BY HAND.
 * Source: the project passed to datagen. Regenerate with: make data
 */
/* OBJ-side video map (vidmap.rs, PLANNING_VIDMAP.md). The engine
   bakes OAM tile bit 8 to 1 for vignettes and battlers: their
   chars stay >= 256 by construction here. */

/* vignettes: 8 slots of 16 chars (4 grid columns x 4 rows) */
#define VID_VIG_CHARS { 384, 388, 392, 396, 448, 452, 456, 460 }
#define VID_VIG_OAMS \
  { 96 << 2, 97 << 2, 98 << 2, 99 << 2, 50 << 2, 51 << 2, 52 << 2, 53 << 2 }
/* scene palette pool for vignettes: {A, B[, C]} — C is the
   weather's palette, in the pool only when no weather command
   exists in the project (0xFF = never matches) */
#define VID_VIG_PAL_A 5
#define VID_VIG_PAL_B 6
#define VID_VIG_PAL_C 0x07

/* posed battlers: 4 cells aliasing vignette slots 4-7 (documented
   exclusivity, vignette.h) */
#define VID_BP_CHAR_BASE 448
#define VID_BP_OAM_BASE 104

/* damage-popup digits: 48 chars, OBJ palette 4 */
#define VID_DIG_CHAR 336
#define VID_DIG_PAL 4
#define VID_POP_OAM_BASE 100

/* weather: two 16x16 blocks (c, c+1, c+16, c+17 each) */
#define VID_WEA_CHAR_RAIN 484
#define VID_WEA_CHAR_SNOW 486
#define VID_WEA_OAM_BASE 100
#define VID_WEA_PAL 7
