/*
 * audio.c — per-scene music and scripted sounds through snesmod
 * (PVSnesLib).
 *
 * The soundbank is generated by smconv from the .it files datagen
 * copies (src/data/music/, in music_id order) and pinned to bank $87.
 * AUDIO_ENABLED comes from datagen: a project without music compiles
 * with no soundbank and no reference to the SOUNDBANK__ symbol.
 *
 * Sounds: 8 kHz BRR samples from data_sfx.c, always emitted. The SPC
 * effect region is sized on the LARGEST sound (SFX_REGION pages of 256
 * bytes) and every spcPlaySound reloads its own there — the PVSnesLib
 * model. spcAllocateSoundRegion CUTS the running module, so it is
 * called at BOOT only, before the first music.
 */
#include <snes.h>
#include "formats.h"
#include "audio.h"
#include "data/audio_cfg.h"

#if AUDIO_ENABLED
extern char SOUNDBANK__;
#endif

#if SFX_COUNT
extern const u8 *const sfx_ptr[];
extern const u16 sfx_len[];
static brrsamples sfx_tab[SFX_COUNT];
#endif

static u8 current_music;

void audio_init(void)
{
#if SFX_COUNT
  u8 i;
#endif

  current_music = MUSIC_NONE;
#if AUDIO_ENABLED || SFX_COUNT
  spcBoot(); /* BRR sounds need the SPC even without music */
#endif
#if AUDIO_ENABLED
  spcSetBank(&SOUNDBANK__);
#endif
#if SFX_COUNT
  spcAllocateSoundRegion(SFX_REGION);
  /* TRAP (read in snesmodwla.asm / sounds.asm): spcSetSoundEntry points
     the SPC table at the LAST structure passed, and spcPlaySound(i)
     reads the entry at "last + i x 8", FORWARD in memory. The entries
     therefore live in a CONTIGUOUS array (brrsamples is exactly 8
     bytes) loaded BACKWARDS: the final call lands on sfx_tab[0], so
     spcPlaySound(sfx_id) indexes the project as it is. Loading them
     forwards played entries from OUTSIDE the array. */
  for (i = SFX_COUNT; i != 0; i--)
    spcSetSoundEntry(15, 8, 4, sfx_len[i - 1], (u8 *)sfx_ptr[i - 1],
                     &sfx_tab[i - 1]);
#endif
}

void audio_play_sfx(u8 sfx_id)
{
#if SFX_COUNT
  if (sfx_id < SFX_COUNT)
    spcPlaySound(sfx_id); /* direct index — see the backwards loading above */
#else
  (void)sfx_id;
#endif
}

void audio_play_music(u8 music_id)
{
  if (music_id == current_music)
    return;
#if AUDIO_ENABLED
  if (current_music != MUSIC_NONE)
    spcStop();
  if (music_id != MUSIC_NONE)
  {
    spcLoad(music_id);
    spcPlay(0);
  }
#endif
  current_music = music_id;
}

void audio_process(void)
{
#if AUDIO_ENABLED
  spcProcess();
#endif
}
