/*
 * picture.c — full-screen pictures (S3, RM2003 style).
 *
 * A picture is compiled by datagen (data_pic{i}.c): deduplicated 4bpp
 * chars (<= 512), a full 32x32 tilemap (image anchored top-left,
 * transparent padding — safe wrap when scrolling) and a 16-colour
 * palette.
 *
 * VRAM plan WITHOUT rebuilding: the image borrows the OBJ REGION
 * ($4000-$6000 words, 512 chars — sprites are hidden while it shows)
 * and its map goes to the FREE region $7000. The tileset chars, the
 * BG1/BG2 maps and the WRAM grids are NEVER touched: closing the image
 * means switching the BG1 registers back, reloading the sprite chars
 * (one DMA) and the BG palettes — event positions and states intact,
 * no map re-windowing (map_init on the way back proved fragile outside
 * the warp path — see the S3 history).
 *
 * While the image is up: BG2 and OBJ removed (REG_TM 0x05), BG1 points
 * at the image's chars and map, BG3 stays above — dialogues and widgets
 * play ON TOP of the image. Transitions follow the do_warp recipe (fade
 * out, screen off, fade in), run from the MAIN LOOP via picture_apply,
 * never from vm_update.
 *
 * S7: per-command fade duration (frames, 0 = instant — an IN-HOUSE
 * fade on $2100, a single division per transition), position clamped
 * to the real dimensions (pic_wt/pic_ht, engine-side centring
 * available), and MOVEPIC: a NON-blocking slide to a target in N
 * frames (8.8 step fixed at command time, advanced each frame by
 * picture_apply — the scroll goes out at VBlank via picture_vblank,
 * nothing else to synchronise).
 */
#include <snes.h>
#include "picture.h"
#include "scene.h"
#include "camera.h"
#include "textbox.h"
#include "screenfx.h"
#include "effectlayer.h"
#include "weather.h"
#include "vignette.h"
#include "vram.h"
#include "vblnmi.h"

/* Register generated by datagen (data_pictures.c — always emitted) */
extern const u8 pic_count;
extern const u8 *const pic_chars[];
extern const u16 *const pic_chars_sizes[];
extern const u16 *const pic_maps[];
extern const u16 *const pic_pals[];
extern const u8 pic_flags[]; /* bit 0 = transparency (S4) */
extern const u8 pic_wt[];    /* width in tiles (S7 — clamp/centring) */
extern const u8 pic_ht[];    /* height in tiles */

/* Scene BG palettes + sprite chars (data_assets.c) — for restoring */
extern const u16 *const gfx_pals[];
extern const u8 *const sprite_chars[];
extern const u16 *const sprite_chars_sizes[];

extern u8 videoMode; /* PVSnesLib mirror of REG_TM ($212C) */

/* Layers of game mode (main.c: setMode BG_MODE1) — BG1|BG2|BG3|OBJ. An
   ENGINE constant, reasserted rather than read back (reliable). */
#define PIC_TM_GAME 0x17
#define PIC_TM_PIC 0x05 /* BG1 (image) + BG3 (dialogues on top) */
#define PIC_TM_TRANS 0x07 /* + BG2: the SCENERY shows through the
    transparent pixels (S4) — not the sprites, their VRAM holds the image */

static u8 pic_on = 0;
static u8 pic_cur = 0; /* displayed id (MOVEPIC clamp) */
/* Deferred request (SHOWPIC/HIDEPIC): the transition runs from the MAIN
   LOOP — same spot as do_warp — never from vm_update. 0 = nothing,
   1 = show, 2 = hide. */
static u8 pic_req = 0;
static u8 pic_req_id = 0;
static u8 pic_req_x = 0;
static u8 pic_req_y = 0;
static u8 pic_req_fl = 0;
static u8 pic_req_dur = 0;
/* current image position in 8.8 (S7 slide) + BG1 scroll */
static u16 pic_px8 = 0;
static u16 pic_py8 = 0;
static u16 pic_hx = 0;
static u16 pic_vy = 0;
/* MOVEPIC slide: 8.8 step per axis (magnitude + sign), target */
static u8 mv_frames = 0;
static u16 mv_sx = 0;
static u16 mv_sy = 0;
static u8 mv_xneg = 0;
static u8 mv_yneg = 0;
static u8 mv_tx = 0;
static u8 mv_ty = 0;

u8 picture_active(void)
{
  return pic_on;
}

void picture_request(u8 show, u8 id, u8 x, u8 y, u8 flags, u8 dur)
{
  pic_req = show ? 1 : 2;
  pic_req_id = id;
  pic_req_x = x;
  pic_req_y = y;
  pic_req_fl = flags;
  pic_req_dur = dur;
}

/* requested position -> displayable position: centring (flags bit 2)
   and clamp to the real dimensions — essential when x/y come out of
   VARIABLES (datagen cannot check them at compile time) */
static u8 pic_fit(u8 want, u8 center, u16 size, u16 max)
{
  u16 lim = max - size;

  if (center)
    return (u8)(lim >> 1);
  if ((u16)want > lim)
    return (u8)lim;
  return want;
}

static void pic_place(u8 x, u8 y)
{
  pic_px8 = (u16)x << 8;
  pic_py8 = (u16)y << 8;
  pic_hx = (u16)(0x100 - x) & 0xFF;
  pic_vy = (u16)(0x100 - y) & 0xFF;
}

/* IN-HOUSE fades on $2100 (S7): duration in frames — blocking, like the
   do_warp recipe (setFadeEffect is a fixed 16 frames; here the author
   chooses). ONE division per transition, then an 8.8 step per frame. */
static void pic_fade_out(u8 dur)
{
  u16 step, lvl;
  u8 f;

  if (!dur)
    return;
  step = 0x0F00 / dur;
  lvl = 0x0F00;
  for (f = 0; f < dur; f++)
  {
    lvl = lvl > step ? lvl - step : 0;
    WaitForVBlank();
    REG_INIDISP = (u8)(lvl >> 8);
  }
}

static void pic_fade_in(u8 dur)
{
  u16 step, lvl;
  u8 f;

  if (!dur)
    return;
  step = 0x0F00 / dur;
  lvl = 0;
  REG_INIDISP = 0; /* no full-screen flash before the first step */
  for (f = 0; f < dur; f++)
  {
    lvl += step;
    if (lvl > 0x0F00)
      lvl = 0x0F00;
    WaitForVBlank();
    REG_INIDISP = (u8)(lvl >> 8);
  }
  REG_INIDISP = 0x0F; /* full brightness reasserted (step rounding) */
}

void picture_apply(void)
{
  u8 r = pic_req;

  pic_req = 0;
  if (r == 1)
    picture_show(pic_req_id);
  else if (r == 2)
    picture_hide();
  /* MOVEPIC slide (S7): one step per frame, snapped onto the target on
     the last one — the scroll goes out at the next VBlank */
  if (pic_on && mv_frames)
  {
    mv_frames--;
    if (!mv_frames)
    {
      pic_px8 = (u16)mv_tx << 8;
      pic_py8 = (u16)mv_ty << 8;
    }
    else
    {
      pic_px8 = mv_xneg ? pic_px8 - mv_sx : pic_px8 + mv_sx;
      pic_py8 = mv_yneg ? pic_py8 - mv_sy : pic_py8 + mv_sy;
    }
    pic_hx = (u16)(0x100 - (pic_px8 >> 8)) & 0xFF;
    pic_vy = (u16)(0x100 - (pic_py8 >> 8)) & 0xFF;
  }
}

void picture_move(u8 x, u8 y, u8 flags, u8 dur)
{
  u16 t8;

  if (!pic_on)
    return;
  x = pic_fit(x, flags & 4, (u16)pic_wt[pic_cur] << 3, 256);
  y = pic_fit(y, flags & 4, (u16)pic_ht[pic_cur] << 3, 224);
  if (!dur)
  {
    mv_frames = 0;
    pic_place(x, y);
    return;
  }
  mv_tx = x;
  mv_ty = y;
  t8 = (u16)x << 8;
  if (t8 >= pic_px8)
  {
    mv_xneg = 0;
    mv_sx = (t8 - pic_px8) / dur;
  }
  else
  {
    mv_xneg = 1;
    mv_sx = (pic_px8 - t8) / dur;
  }
  t8 = (u16)y << 8;
  if (t8 >= pic_py8)
  {
    mv_yneg = 0;
    mv_sy = (t8 - pic_py8) / dur;
  }
  else
  {
    mv_yneg = 1;
    mv_sy = (pic_py8 - t8) / dur;
  }
  mv_frames = dur;
}

void picture_show(u8 id)
{
  u8 x, y;

  if (id >= pic_count)
    return;
  pic_fade_out(pic_req_dur);
  setScreenOff();
  vn_cancel_scene(); /* BG1's map now belongs to the image: a pending
      map row landing there would punch tiles through it (V-NMI V3) */
  pic_on = 1;
  pic_cur = id;
  mv_frames = 0;
  /* image with transparency (S4): the scenery layer (BG2, lower layer)
     stays visible behind the punched-out pixels */
  videoMode = (pic_flags[id] & 1) ? PIC_TM_TRANS : PIC_TM_PIC;
  REG_TM = videoMode;
  /* BG1 rebased on the OBJ region (chars) + 32x32 map in the free area —
     the scene's tileset and maps stay intact in VRAM */
  bgSetGfxPtr(0, VRAM_OBJ_GFX);
  bgSetMapPtr(0, VRAM_PIC_MAP, SC_32x32);
  dmaCopyVram((u8 *)pic_chars[id], VRAM_OBJ_GFX, *pic_chars_sizes[id]);
  dmaCopyVram((u8 *)pic_maps[id], VRAM_PIC_MAP, 32 * 32 * 2);
  if (pic_flags[id] & 1)
  {
    /* transparency: the image lives on BG PALETTE 7 (reserved, map
       entries marked by datagen) — the scenery's palettes 0-6 and the
       backdrop colour stay those of the scene */
    dmaCopyCGram((u8 *)pic_pals[id] + 2, 113, 30);
  }
  else
    dmaCopyCGram((u8 *)pic_pals[id], 0, 32); /* colours 0-15 */
  /* screen position (S5/S7): centring/clamp to the real dimensions — the
     coordinates can come out of variables, never trust them */
  x = pic_fit(pic_req_x, pic_req_fl & 4, (u16)pic_wt[id] << 3, 256);
  y = pic_fit(pic_req_y, pic_req_fl & 4, (u16)pic_ht[id] << 3, 224);
  pic_place(x, y);
  /* blending (S8, flags bits 3-4): the image blends with the SCENERY via
     the color math — BG2 goes to the sub screen, the operation applies
     to BG1 alone (BG3 dialogues stay crisp). Tint and flash are held
     while the image is up (same circuit — screenfx_cm_hold). Empty sub
     screen: the hardware falls back on the fixed colour, NO division. */
  x = (pic_req_fl >> 3) & 3;
  if (x)
  {
    y = x == 1 ? 0x41 /* semi-transparent (add + half) */
               : (x == 2 ? 0x01 /* additive */
                         : 0x81 /* subtractive */);
    REG_TS = 0x02; /* BG2 alone in sub — NEVER OBJ (chars = the image) */
    REG_CGWSEL = 0x02;
    REG_CGADSUB = y;
    screenfx_cm_hold_regs(0x02, 0x02, y); /* lightning puts them back (S13) */
    screenfx_cm_hold(1);
  }
  else
  {
    REG_TS = 0;
    screenfx_cm_hold(0);
  }
  bgSetScroll(0, pic_hx, pic_vy);
  screenfx_warp_reset(); /* scripted fade resynced (warp recipe) */
  setScreenOn();
  pic_fade_in(pic_req_dur);
}

void picture_hide(void)
{
  if (!pic_on)
    return;
  pic_fade_out(pic_req_dur);
  setScreenOff();
  /* Sprite chars (the OBJ region was carrying the image) + the scene's
     BG palettes (the image overwrote CGRAM 0-15) */
  dmaCopyVram((u8 *)sprite_chars[scene_ctx.sprite_set_id], VRAM_OBJ_GFX,
              *sprite_chars_sizes[scene_ctx.sprite_set_id]);
  weather_load(); /* weather chars (S13) — the picture took the OBJ region */
  vig_reload();   /* frames + palettes of the active vignettes (B5) */
  dmaCopyCGram((u8 *)gfx_pals[scene_ctx.tileset_id], 0, 128 * 2);
  {
    u16 black = 0; /* backdrop (CGRAM 0) reasserted BLACK — as scene_load */

    dmaCopyCGram((u8 *)&black, 0, 2);
  }
  textbox_load_pal(); /* CGRAM 16-19 (font) overwritten by the BG palettes */
  if (effect_active())
  {
    /* scene with an effect layer (S9): BG1 takes back the PATTERN, not
       the upper layer — registers + color math + palette 7 (the pattern
       VRAM has not moved, the picture lived elsewhere) */
    effect_restore();
  }
  else
  {
    /* The scene's BG1 registers (chars and map were never overwritten) */
    bgSetGfxPtr(0, VRAM_BG1_GFX);
    bgSetMapPtr(0, VRAM_BG1_MAP, SC_64x64);
    REG_TS = 0; /* S8 blend: sub screen given back, tint reasserted */
    screenfx_cm_hold(0);
    bgSetScroll(0, camera.x, camera.y);
  }
  bgSetScroll(1, camera.x, camera.y);
  videoMode = PIC_TM_GAME;
  REG_TM = PIC_TM_GAME;
  pic_on = 0;
  mv_frames = 0;
  screenfx_warp_reset();
  setScreenOn();
  pic_fade_in(pic_req_dur);
}

void picture_vblank(void)
{
  bgSetScroll(0, pic_hx, pic_vy);
}

void picture_reset(void)
{
  if (!pic_on)
    return;
  videoMode = PIC_TM_GAME;
  REG_TM = PIC_TM_GAME;
  REG_TS = 0; /* S8 blend released — do_warp reasserts the tint */
  screenfx_cm_hold(0);
  pic_on = 0; /* scene_load (warp) reloads tileset, sprites and scrolls */
  mv_frames = 0;
}
