/*
 * scene.c — data-driven scene loading from the binary format (spec §1):
 * a Scene Table at $82:8000, structures holding 24-bit far pointers.
 *
 * The engine contains NO game data: everything comes from the data
 * banks generated by tools/datagen. A 24-bit far pointer in a structure
 * is [bank][addr lo][addr hi].
 */
#include <snes.h>
#include "formats.h"
#include "scene.h"
#include "tileanim.h"
#include "rom_layout.h"
#include "vram.h"
#include "map.h"
#include "effectlayer.h"
#include "weather.h"

/* GFX sets (data_assets.c), compiled PER SCENE by datagen: only the
   tiles a scene uses are in VRAM, with multiple palettes baked into the
   BG entries. The tables are indexed by gfx_set_id (header byte 1).
   Arrays of pointers, because indexing those is reliable under tcc,
   unlike bare u16 arrays — docs/ENGINE_CONSTRAINTS.md §1.5. */
extern const u8 *const gfx_chars[];
extern const u16 *const gfx_chars_sizes[];
extern const u16 *const gfx_metas[];
extern const u8 *const gfx_prios[];
extern const u16 *const gfx_pals[];

SceneCtx scene_ctx;

/* Row offsets of the current grid (see scene_load) — avoids the
   software multiply in scene_collision, which the hot paths call.
   Filled at load time, so no static init is needed. */
static u16 col_row_ofs[256];

/* Grids expanded into WRAM: scenes travel RLE-compressed in ROM
   (spec §1.6) and are unpacked here at load time — a budget of 8192
   cells per grid, checked by datagen.
   DEFINED IN ASSEMBLY (../wram7f.asm), in bank $7F: tcc-816's .bss only
   has $7E:2000-$7FFF, and past that it silently overwrites PVSnesLib's
   shadow OAM. See docs/ENGINE_CONSTRAINTS.md §3. */
#define MAP_BUF_CELLS 8192
extern u8 scn_lower[MAP_BUF_CELLS];
extern u8 scn_upper[MAP_BUF_CELLS];
extern u8 scn_col[MAP_BUF_CELLS];

/* RLE (spec §1.6): [count 1-255][value] pairs, up to `cells` bytes */
static void rle_decode(u8 *dst, const u8 *src, u16 cells)
{
  u16 i = 0;
  u8 n, v;

  while (i < cells)
  {
    n = *src++;
    v = *src++;
    while (n--)
      dst[i++] = v;
  }
}

/* Debug halt: valid data can never reach here. A full RED screen, so it
   is immediately recognisable on the harness. */
static void scene_halt(void)
{
  u16 red = 0x001F;

  setBrightness(15);
  dmaCopyCGram((u8 *)&red, 0, 2);
  while (1)
  {
  }
}

/* Reads a 24-bit far pointer from the binary format (spec §1.2) */
static const u8 *read_far(const u8 *p)
{
  return make_far(p[0], (u16)p[1] | ((u16)p[2] << 8));
}

u8 scene_boot_id(void)
{
  const u8 *tbl = make_far(BANK_SCENES, BANK_BASE_ADDR);

  return tbl[2]; /* Scene Table v0.2: boot_scene_id at offset 2 */
}

void scene_load(u8 scene_id)
{
  const u8 *tbl = make_far(BANK_SCENES, BANK_BASE_ADDR);
  u16 scene_count = (u16)tbl[0] | ((u16)tbl[1] << 8);
  const u8 *entry;
  const u8 *h;

  if (scene_id >= scene_count)
    scene_halt();

  /* Table entry: { bank (u8), addr (u16), reserved } — spec §1.1 */
  entry = tbl + 4 + ((u16)scene_id << 2);
  h = make_far(entry[0], (u16)entry[1] | ((u16)entry[2] << 8));

  /* The scene_type field is checked even though there is only one type */
  if (h[0] != SCENE_TYPE_TOP_DOWN)
    scene_halt();

  /* Scene Header (spec §1.2) -> WRAM copy plus resolved pointers */
  scene_ctx.scene_type = h[0];
  scene_ctx.map_w = h[2];
  scene_ctx.map_h = h[3];
  scene_ctx.actors = (const ActorDef *)read_far(h + 10);
  scene_ctx.scripts = read_far(h + 13);
  scene_ctx.actor_count = h[16];
  scene_ctx.player_start_x = h[17];
  scene_ctx.player_start_y = h[18];
  scene_ctx.tileset_id = h[1];
  scene_ctx.music_id = h[19];
  scene_ctx.warps = (const WarpDef *)read_far(h + 20);
  scene_ctx.warp_count = h[23];
  scene_ctx.sprite_set_id = h[27]; /* sprites compiled per scene */
  scene_ctx.scene_id = scene_id; /* saves (spec §4bis) */

  /* Precomputed row offsets: scene_collision is called ~15 times per
     walking frame (hero plus NPC collision), and tcc-816's software
     multiply at every call weighs on the frame budget. map_h is a u8,
     so 256 entries cover every scene. */
  {
    u16 o = 0;
    u16 r;

    for (r = 0; r < scene_ctx.map_h; r++)
    {
      col_row_ofs[r] = o;
      o += scene_ctx.map_w;
    }
  }

  /* RLE grids -> WRAM (spec §1.6): lower, collision, upper */
  {
    u16 cells = (u16)scene_ctx.map_w * scene_ctx.map_h;

    if (cells > MAP_BUF_CELLS)
      scene_halt(); /* datagen checks the limit: corrupt data */
    rle_decode(scn_lower, read_far(h + 4), cells);
    rle_decode(scn_col, read_far(h + 7), cells);
    rle_decode(scn_upper, read_far(h + 24), cells);
    scene_ctx.tilemap = scn_lower;
    scene_ctx.collision = scn_col;
    scene_ctx.tilemap_upper = scn_upper;
  }

  /* The scene's tileset (chars, palette, metatile table) — screen off,
     so the DMA transfers are safe (forced blank). map_init() fills the
     tilemap once the camera is positioned.
     NB: never name a symbol "metatiles" — it collides silently with an
     internal PVSnesLib symbol (maps.asm). */
  /* Full BG CGRAM: 8 palettes of 16 colours (the BG entries carry the
     palette bits 10-12, baked by datagen) */
  bgInitTileSet(0, (u8 *)gfx_chars[scene_ctx.tileset_id],
                (u8 *)gfx_pals[scene_ctx.tileset_id], 0,
                *gfx_chars_sizes[scene_ctx.tileset_id], 128 * 2,
                BG_16COLORS, VRAM_BG1_GFX);
  {
    /* The BACKDROP colour (CGRAM 0) is forced BLACK: BG tiles never draw
       index 0, so only an EMPTY cell — the eraser on the lower layer —
       shows it. Predictable whatever the tileset. */
    u16 black = 0;

    dmaCopyCGram((u8 *)&black, 0, 2);
  }
  /* Two layers (RM2003 model): BG1 upper, BG2 lower, shared charset */
  bgSetMapPtr(0, VRAM_BG1_MAP, SC_64x64);
  bgSetGfxPtr(1, VRAM_BG1_GFX);
  bgSetMapPtr(1, VRAM_BG2_MAP, SC_64x64);
  map_set_metatiles(gfx_metas[scene_ctx.tileset_id],
                    gfx_prios[scene_ctx.tileset_id]);
  /* Effect layer: when the scene has one, BG1 is rebased onto the
     pattern and the upper layer is ignored */
  effect_load(scene_id);
  tileanim_init(scene_id); /* animated tiles — the scene's sequences */
  /* weather: chars and palette are reloaded by player_init, whose
     oamInitGfxSet overwrites the 128 OBJ colours including the
     particles' palette 7 — so this call must come AFTER */
}

u8 scene_collision(u8 tx, u8 ty)
{
  return scene_ctx.collision[col_row_ofs[ty] + tx];
}
