/*
 * tileanim.c — animated scenery tiles. See tileanim.h.
 *
 * Data (data_tileanim.c, generated by datagen):
 *   ta_first[scene]  first sequence of the scene (bounds s..s+1)
 *   ta_ffirst[seq]   first frame of the sequence (bounds f..f+1)
 *   ta_mode[seq]     0 = 1-2-3 (loop), 1 = 1-2-3-2 (ping-pong)
 *   ta_speed[seq]    display frames per step
 *   ta_dest[seq*4]   the 4 VRAM chars of the base tile
 *   ta_src[frame*4]  the 4 ROM chars of each frame (scene charset)
 *
 * A STEP is 128 bytes, and only one sequence passes per VBlank; the
 * others retry next frame. Queues stay short, so there is never a peak.
 *
 * Those 128 bytes used to go out in FOUR DMA calls, and a step cost 18
 * screen lines for 0.75 line of actual transfer — see vramjob.h. Two
 * fixes: the transfer plan is built in tileanim_update(), outside the
 * VBlank window, and chars that are CONSECUTIVE on both sides at once
 * are merged. The common case is a 16x16 tile whose four quarters
 * follow each other in ROM as in VRAM: one 128-byte transfer. When
 * datagen's deduplication has broken the run we fall back to two or
 * three — that is verified, not assumed.
 */
#include <snes.h>
#include "formats.h"
#include "scene.h"
#include "tileanim.h"
#include "vbudget.h"
#include "vram.h"
#include "vramjob.h"
#include "vblnmi.h"

extern const u8 ta_first[];
extern const u8 ta_ffirst[];
extern const u8 ta_mode[];
extern const u8 ta_speed[];
extern const u16 ta_dest[];
extern const u16 ta_src[];
extern const u8 *const gfx_chars[]; /* ROM charsets per gfx set (scene.c) */

#define TA_MAX 8 /* simultaneous sequences per scene */

/* explicit init: tcc-816 does not clear .bss */
static u8 ta_n = 0;       /* active sequences of the current scene */
static u8 ta_base = 0;    /* global index of the first */
static u8 ta_cnt[TA_MAX]; /* countdown per sequence */
static u8 ta_pos[TA_MAX]; /* position in the cycle */
static u8 ta_pend = 0xFF; /* sequence whose step is IN FLIGHT on the
    dispatcher (V-NMI V3) — 0xFF free. One step at a time, as always;
    the descriptor's token is the authority, this mirrors it so the
    update loop knows when to arm the next step. */
static u8 ta_pfrm = 0;    /* frame (global index) of the pending step */
static u16 ta_njobs = 0;  /* transfers in the pending plan (1 to 4) */

void tileanim_init(u8 scene_id)
{
  u8 i;

  ta_base = ta_first[scene_id];
  ta_n = (u8)(ta_first[scene_id + 1] - ta_base);
  if (ta_n > TA_MAX)
    ta_n = TA_MAX;
  for (i = 0; i < ta_n; i++)
  {
    ta_cnt[i] = ta_speed[ta_base + i];
    ta_pos[i] = 0;
  }
  ta_pend = 0xFF; /* a step from the previous scene must never fire */
  ta_njobs = 0;
  vn_cancel(VN_TA); /* including one already published: its gfx_chars
                       source died with the scene */
}

/* Builds the transfer plan for the armed step. Called from
   tileanim_update, so OUTSIDE the VBlank window — that is the whole
   point: the long indirection through gfx_chars[] and the eight array
   reads are paid on display time, where there is some to spare.

   Two chars that follow each other in ROM AND in VRAM fit in the same
   transfer. The condition covers BOTH sides: datagen deduplicates
   identical chars, so a tile with two similar quarters breaks the run
   on the source side without breaking it on the destination side. */
static void ta_plan(void)
{
  const u8 *chars;
  u16 s4, f4, sc, dc, psc, pdc;
  u8 k;

  chars = gfx_chars[scene_ctx.tileset_id];
  s4 = (u16)(ta_base + ta_pend) << 2;
  f4 = (u16)ta_pfrm << 2;
  ta_njobs = 0;
  psc = 0;
  pdc = 0;
  for (k = 0; k < 4; k++)
  {
    sc = ta_src[f4 + k];
    dc = ta_dest[s4 + k];
    if (ta_njobs && sc == (u16)(psc + 1) && dc == (u16)(pdc + 1))
      vj_len[VJ_TILEANIM + ta_njobs - 1] += 32; /* the run continues */
    else
    {
      /* 32 bytes per 4bpp char: ROM (scene charset) -> tileset region */
      vj_set((u16)(VJ_TILEANIM + ta_njobs), chars + ((u32)sc << 5),
             (u16)(VRAM_BG1_GFX + (dc << 4)), 32);
      ta_njobs++;
    }
    psc = sc;
    pdc = dc;
  }
}

void tileanim_update(void)
{
  u8 i, s, nf, cyc, f;

  if (ta_pend != 0xFF && !vn_busy(VN_TA))
    ta_pend = 0xFF; /* the step landed (either lane): free the seat */
  for (i = 0; i < ta_n; i++)
  {
    if (ta_cnt[i])
    {
      ta_cnt[i]--;
      continue;
    }
    if (ta_pend != 0xFF)
      continue; /* one step per VBlank; this one will retry */
    s = (u8)(ta_base + i);
    nf = (u8)(ta_ffirst[s + 1] - ta_ffirst[s]);
    /* cycle: 1-2-3 is nf steps, 1-2-3-2 is 2*nf-2 (ping-pong) */
    cyc = (ta_mode[s] && nf > 2) ? (u8)((nf << 1) - 2) : nf;
    ta_pos[i]++;
    if (ta_pos[i] >= cyc)
      ta_pos[i] = 0;
    f = ta_pos[i] < nf ? ta_pos[i] : (u8)((nf << 1) - 2 - ta_pos[i]);
    ta_pend = i;
    ta_pfrm = (u8)(ta_ffirst[s] + f);
    ta_cnt[i] = ta_speed[s];
    ta_plan();
    /* Published, not fired: the dispatcher's lanes take it from here
       (V-NMI V3). VN_TA walks LAST in the table — the animated tile
       step keeps its historical role of first sacrifice under a
       short window, and it retries as long as the token stands. */
    vn_publish_burst(VN_TA, VJ_TILEANIM, ta_njobs, VJ_INC1,
                     VBL_COST_BURST(ta_njobs, 128));
  }
}
